apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
spec:
 replicas: 2
 selector:
 matchLabels:
   name: app
  
 template:
   metadata:
     name: httpd-deploy
     label:
      name: app
   spec:
     containers:
      - name: httpd
        image: httpd
        ports:
         - containerPort: 80
  
