apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
spec:
 replicas: 3
 selector:
  matchLabels:
   name: app
  
 template:
   metadata:
     name: httpd-deploy
     labels:
      name: app
   spec:
     containers:
      - name: httpd
        image: aviraj3109/custom-httpd:v2
        ports:
         - containerPort: 80
  
